use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true

target 'JTUtils_Example' do
  pod 'JTUtils', :path => '../'

  target 'JTUtils_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
