disabled_rules:
  - line_length
  - type_name
  - large_tuple
  - multiple_closures_with_trailing_closure
  - identifier_name
  - type_body_length
  - force_try
  - force_cast

opt_in_rules:
  - empty_count
  - force_unwrapping

included:
  - JTUtils/Classes

excluded:
  - Example/Pods
  - JTUtils/Classes/HTMLEntities

function_body_length:
  warning: 50
