# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage
# * https://jasontaiworkspace.slack.com/apps/A0F81FP4N-travis-ci?next_id=0
# * https://docs.travis-ci.com/user/tutorial/

osx_image: xcode11
language: objective-c
# xcode_workspace: Example/MDictParser.xcworkspace
# xcode_scheme: platform=iOS Simulator,name=iPhone XÊ€,OS=13.0

# cache: cocoapods
podfile: Example/Podfile
before_install:
- bundle install
- pod install --project-directory=Example
- mkdir -p test_output
script:
# - bundle exec fastlane ci_test
# - bundle exec danger
# - pod lib lint --allow-warnings --sources=https://github.com/tjcjc/Specs.git,https://github.com/CocoaPods/Specs.git
- pod repo add Jason https://github.com/tjcjc/Specs
- pod repo push Jason JTUtils.podspec --allow-warnings
after_success:
# - bash <(curl -s https://codecov.io/bash) -t 92e9812b-4072-4fd4-970b-785aba1aeba9
# - pod repo add Jason https://github.com/tjcjc/Specs
# - pod repo push Jason JTUtils.podspec --allow-warnings
notifications:
  slack: jasontaiworkspace:lMmPD9sNdKpuFERKU0i73cj4
  email: false